batch_size: 4
image_shape: [256, 256, 3]

train_dir: ../../dataset/coco2014/train2014
valid_dir: ../../dataset/coco2014/val2014
results_dir: data/results
eval_image_path: data/content/stata.jpg
style_image_path: data/style/wave.jpg
style_weights: 100
style_layers: [relu1_1, relu2_1, relu3_1, relu4_1, relu5_1]
content_weight: 2
content_layer: relu4_2
tv_weight: 200

vgg_path: 'data/imagenet-vgg-verydeep-19.mat'

model_root_dir: saved_models            # root path for savinng models
log_root_dir: logs                      # root path for tensorboard logs
model_name: baseline

n_iterations: 50000

style_transfer:
    conv_params: [[32, 9, 1], [64, 3, 2], [128, 3, 2]]  # filters, kernel_size, strides
    n_residuals: 5
    convtras_params: [[64, 3, 2], [32, 3, 2]]
    final_conv_params: [3, 9, 1]
    padding: reflect
    norm: instance
    learning_rate: 1e-3
