batch_size: 16
image_shape: [128, 128, 3]

train_dir: ../../dataset/celebA

# model path: model_root_dir/model_name
# tensorboard path: log_root_dir/model_name
model_root_dir: saved_models            # root path for savinng models
log_root_dir: logs  # root path for tensorboard logs
model_name: baseline

n_iterations: 5000000

generator:
    spectral_norm: True
    activation: relu
    padding: same
    z_dim: 128
    learning_rate: 0.0001
    beta1: 0
    beta2: 0.9

discriminator:
    spectral_norm: True
    activation: lrelu
    padding: same
    lrelu_slope: 0.2
    learning_rate: 0.0003
    beta1: 0
    beta2: 0.9
