batch_size: 32
image_shape: [128, 128, 3]

train_dir: ../../dataset/celebA

# model path: model_root_dir/model_name
# tensorboard path: log_root_dir/model_name
model_root_dir: saved_models            # root path for savinng models
log_root_dir: logs  # root path for tensorboard logs
model_name: baseline

n_iterations: 5000000

generator:
    convtrans_params: [[512, 3, 1], [256, 3, 1], [128, 3, 1], [64, 3, 1], [32, 3, 1]]
    attention_layers: [3]    # Insert attention to i-th convtras layer. Indices start from 0
    spectral_norm: True
    activation: relu
    padding: reflect
    z_dim: 128
    learning_rate: 0.0001
    beta1: 0
    beta2: 0.9

discriminator:
    conv_params: [[64, 4, 2], [128, 4, 2], [256, 4, 2], [512, 4, 2], [1024, 4, 2]]
    attention_layers: [1]    # Insert attention to i-th conv layer. Indices start from 0
    spectral_norm: True
    activation: lrelu
    padding: reflect
    lrelu_slope: 0.2
    learning_rate: 0.0004
    beta1: 0
    beta2: 0.9
