batch_size: 32
image_shape: [128, 128, 3]

train_dir: ../../dataset/celebA
results_dir: data/results
eval_batch_size: 60
# model path: model_root_dir/model_name
# tensorboard path: log_root_dir/model_name
model_root_dir: saved_models            # root path for savinng models
log_root_dir: logs  # root path for tensorboard logs
model_name: baseline

n_iterations: 5000000

generator:
    spectral_norm: True
    activation: relu
    padding: same
    z_dim: 128
    learning_rate: 5e-5
    beta1: 0
    # beta2: 0.9

discriminator:
    spectral_norm: True
    activation: lrelu
    lrelu_slope: 0.2
    padding: same
    learning_rate: 1e-4
    beta1: 0
    # beta2: 0.9
