batch_size: 64
color: False
image_shape: [28, 28, 3]
code_size: 64   
gan_coeff: 1    # coefficient for gan loss,train weight
cpc_coeff: 10   # coefficient for cpc loss,train weight


# model path: model_root_dir/model_name
# tensorboard path: log_root_dir/model_name
model_root_dir: saved_models            # root path for savinng models
log_root_dir: logs  # root path for tensorboard logs
model_name: baseline

cpc:
    learning_rate: 0.0001
    weight_decay: 0.0001
    context_size: 256  #rnn gru cell size
    hist_terms: 4
    future_terms: 4
gan:
    learning_rate: 0.0001
    weight_decay: 0.0001
    noise_size: 10  #noise dim
    critic_coeff: 1.  # weight